/* Question 1 */
Select ORDER_NUM, ORDER_DATE, c.CUSTOMER_NUM, c.CUSTOMER_NAME
From Orders o
INNER JOIN Customer c
ON o.CUSTOMER_NUM = c.CUSTOMER_NUM;

/* Question 2 */
Select ORDER_NUM, ORDER_DATE, c.CUSTOMER_NUM, c.CUSTOMER_NAME
FROM ORDERS o
INNER JOIN CUSTOMER c
WHERE ORDER_DATE = '2015-10-15';

/* Question 3 */
Select o.ORDER_NUM, ORDER_DATE, ITEM_NUM, NUM_ORDERED, QUOTED_PRICE
FROM Orders o
INNER JOIN Order_Line ol
ON o.ORDER_NUM = ol.ORDER_NUM;

/* Question 4 */
SELECT o.ORDER_NUM, o.ORDER_DATE, ol.ITEM_NUM, i.DESCRIPTION, i.CATEGORY
FROM Orders o
INNER JOIN Order_Line ol
ON o.ORDER_NUM = ol.ORDER_NUM
INNER JOIN Item i
On ol.ITEM_NUM = i.ITEM_NUM;

/* Question 5 */
SELECT o.ORDER_NUM, o.ORDER_DATE, ol.ITEM_NUM, i.DESCRIPTION, i.CATEGORY
FROM Orders o
INNER JOIN Order_Line ol
ON o.ORDER_NUM = ol.ORDER_NUM
INNER JOIN Item i
On ol.ITEM_NUM = i.ITEM_NUM
ORDER BY i.CATEGORY, o.ORDER_NUM;

/* Question 6 */
SELECT r.REP_NUM, r.LAST_NAME, r.FIRST_NAME, c.CREDIT_LIMIT
FROM REP r
INNER JOIN Customer c
WHERE CREDIT_LIMIT = '10000'
GROUP BY REP_NUM;

/* Question 7 */
SELECT c.CUSTOMER_NUM, CUSTOMER_NAME, o.ORDER_NUM, ol.ITEM_NUM, i.DESCRIPTION
FROM CUSTOMER c
JOIN ORDERS o
ON c.CUSTOMER_NUM = o.CUSTOMER_NUM
JOIN ORDER_LINE ol
ON o.ORDER_NUM = ol.ORDER_NUM
JOIN ITEM i
ON ol.ITEM_NUM = i.ITEM_NUM
WHERE DESCRIPTION = 'Rocking Horse';

/* Question 8 */
SELECT o.ORDER_NUM, ORDER_DATE, c.CUSTOMER_NAME
FROM ORDERS o
JOIN CUSTOMER c
ON o.CUSTOMER_NUM = c.CUSTOMER_NUM
WHERE CUSTOMER_NAME LIKE 'Johnson%';

/* Question 9 */
SELECT o.ORDER_NUM, o.ORDER_DATE, i.DESCRIPTION
FROM ORDERS o
JOIN ORDER_LINE ol
ON o.ORDER_NUM = ol.ORDER_NUM
JOIN ITEM i
ON ol.ITEM_NUM = i.ITEM_NUM
WHERE DESCRIPTION = 'FIRE ENGINE';

/* Question 10 */
SELECT i.ITEM_NUM, i.DESCRIPTION, i.ON_HAND, ol.ORDER_NUM, ol.NUM_ORDERED
FROM ITEM i
LEFT JOIN ORDER_LINE ol
ON i.ITEM_NUM = ol.ITEM_NUM
ORDER BY ITEM_NUM;

/* Question 11 */
SELECT c.CUSTOMER_NUM, c.CUSTOMER_NAME, r.LAST_NAME, r.FIRST_NAME
FROM CUSTOMER c
RIGHT JOIN REP r
ORDER REP_NUM

/* Question 12 */
SELECT r.REP_NUM, SUM(BALANCE)
FROM CUSTOMER c
Right JOIN REP r
ON C.REP_NUM = r.REP_NUM
GROUP BY REP_NUM

/* Question 13 */
SELECT r.REP_NUM, SUM(BALANCE)
FROM CUSTOMER c
RIGHT JOIN REP r
ON C.REP_NUM = r.REP_NUM
GROUP BY REP_NUM
HAVING SUM(BALANCE) > 5000;

/* Question 14 */
SELECT c.CUSTOMER_NUM, c.CUSTOMER_NAME, AVG(QUOTED_PRICE)
FROM CUSTOMER c
JOIN ORDERS o
ON c.CUSTOMER_NUM = o.CUSTOMER_NUM
JOIN ORDER_LINE ol
GROUP BY c.CUSTOMER_NAME
ORDER BY AVG(QUOTED_PRICE)

/* Question 15 */




/* Question 16 */
SELECT SUM(BALANCE)
FROM CUSTOMER
GROUP BY REP_NUM



/* Question 17 */


/* Question 18 */


/* Question 19 */


/* Question 20 */


/* Question 21 */

